tap "homebrew/bundle"
tap "noahgorstein/tap"
tap "noborus/tap"
tap "orangekame3/tap"
tap "teamookla/speedtest"
brew "little-cms2"
brew "jpeg-xl"
brew "aom"
brew "bash"
brew "bat"
brew "boxes"
brew "btop"
brew "fontconfig"
brew "glib"
brew "cmatrix"
brew "colordiff"
brew "coreutils"
brew "cowsay"
brew "dasel"
brew "diff-so-fancy"
brew "difftastic"
brew "duf"
brew "entr"
brew "eza"
brew "fd"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "openjpeg"
brew "leptonica"
brew "libass"
brew "libbluray"
brew "pango"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "figlet"
brew "findutils"
brew "fnm"
brew "fzf"
brew "forgit"
brew "fortune"
brew "freetds"
brew "fx"
brew "gawk"
brew "libavif"
brew "gd"
brew "gh"
brew "ghostscript"
brew "git-delta"
brew "gnu-sed"
brew "gobject-introspection"
brew "gping"
brew "groovy"
brew "guile"
brew "gum"
brew "htmlq"
brew "htop"
brew "httpie"
brew "hurl"
brew "libheif"
brew "imagemagick"
brew "jo"
brew "jq"
brew "jsonpp"
brew "lazydocker"
brew "lazygit"
brew "luarocks"
brew "mailsy"
brew "mas"
brew "maven"
brew "mdless"
brew "midnight-commander"
brew "mkcert"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "nginx"
brew "nss"
brew "php"
brew "pipx"
brew "pup"
brew "pyenv"
brew "python-setuptools"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "qemu"
brew "rclone"
brew "ripgrep"
brew "sl"
brew "starship"
brew "stow"
brew "superfile"
brew "tag"
brew "tealdeer"
brew "telnet"
brew "tmux"
brew "toilet"
brew "tree"
brew "wakeonlan"
brew "wget"
brew "wifi-password"
brew "xh"
brew "yazi"
brew "yt-dlp"
brew "yq"
brew "yt-dlp"
brew "zoxide"
brew "noahgorstein/tap/jqp"
brew "noborus/tap/trdsql"
brew "orangekame3/tap/paclear"
brew "teamookla/speedtest/speedtest"
cask "1password-cli", args: { appdir: "/Applications" }
cask "a-better-finder-rename", args: { appdir: "/Applications" }
cask "affinity-photo", args: { appdir: "/Applications" }
cask "affinity-publisher", args: { appdir: "/Applications" }
cask "alacritty"
cask "applite"
cask "audio-hijack", args: { appdir: "/Applications" }
cask "bunch", args: { appdir: "/Applications" }
cask "devtoys", args: { appdir: "/Applications" }
cask "dropzone", args: { appdir: "/Applications" }
cask "elgato-stream-deck", args: { appdir: "/Applications" }
cask "fujitsu-scansnap-home", args: { appdir: "/Applications" }
cask "inkscape"
cask "jordanbaird-ice"
cask "kitty"
cask "knockknock", args: { appdir: "/Applications" }
cask "loopback", args: { appdir: "/Applications" }
cask "makemkv", args: { appdir: "/Applications" }
cask "moom", args: { appdir: "/Applications" }
cask "onyx", args: { appdir: "/Applications" }
cask "plex", args: { appdir: "/Applications" }
cask "qmk-toolbox", args: { appdir: "/Applications" }
cask "radio-silence", args: { appdir: "/Applications" }
cask "retrobatch", args: { appdir: "/Applications" }
cask "screenflow", args: { appdir: "/Applications" }
cask "shortcat"
cask "transmission", args: { appdir: "/Applications" }
cask "wezterm"
vscode "adpyke.codesnap"
vscode "akarlsten.vscode-snazzy-akarlsten"
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "angular.ng-template"
vscode "bierner.markdown-preview-github-styles"
vscode "bito.bito"
vscode "cssho.vscode-svgviewer"
vscode "csstools.postcss"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "exodiusstudios.comment-anchors"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-pull-request-github"
vscode "humao.rest-client"
vscode "jaredkent.laserwave"
vscode "johnpapa.angular2"
vscode "johnpapa.vscode-peacock"
vscode "mike-co.import-sorter"
vscode "mrmlnc.vscode-duplicate"
vscode "ms-playwright.playwright"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "orta.vscode-twoslash-queries"
vscode "phoenisx.cssvar"
vscode "pranaygp.vscode-css-peek"
vscode "redhat.vscode-xml"
vscode "richie5um2.vscode-sort-json"
vscode "ritwickdey.liveserver"
vscode "ronnidc.nunjucks"
vscode "samrapdev.outrun"
vscode "sdras.night-owl"
vscode "sjuulwijnia.kx-vscode-angular-context-creator"
vscode "sonarsource.sonarlint-vscode"
vscode "spywhere.guides"
vscode "stylelint.vscode-stylelint"
vscode "techer.open-in-browser"
vscode "timonwong.shellcheck"
vscode "tyriar.sort-lines"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "waderyan.gitblame"
vscode "wesbos.theme-cobalt2"
vscode "wicked-labs.wvsc-serendipity"
vscode "zignd.html-css-class-completion"
